# Generated by Django 5.0.7 on 2024-09-27 01:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "office",
                    models.CharField(
                        choices=[
                            ("VP Administration and Finance", "Admin and Finance"),
                            ("VP Academic Affairs", "VP Academic Affairs"),
                            (
                                "VP Students and External Affairs",
                                "VP Students and External Affairs",
                            ),
                            ("GAD Office", "GAD Office"),
                        ],
                        max_length=50,
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("urgency", models.CharField(max_length=50)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="complaint_pdfs/"
                    ),
                ),
                ("issue_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_sent", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Informant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("employee", "Employee"),
                            ("faculty", "Faculty"),
                        ],
                        max_length=10,
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STCS", "School of Technology and Computer Science"),
                            ("SCJE", "School of Criminal Justice and Education"),
                            ("SAS", "School of Arts and Sciences"),
                            ("SME", "School of Management and Entrepreneurship"),
                            ("SOE", "School of Engineering"),
                            ("SNHS", "School of Nursing and Health Sciences"),
                            ("LHS", "Liberal Arts and Humanities"),
                            ("STED", "School of Teacher Education"),
                        ],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "student_id_file",
                    models.ImageField(blank=True, null=True, upload_to="student_ids/"),
                ),
                (
                    "employee_id_file",
                    models.ImageField(blank=True, null=True, upload_to="employee_ids/"),
                ),
                (
                    "study_load_file",
                    models.ImageField(blank=True, null=True, upload_to="study_loads/"),
                ),
                (
                    "document_file",
                    models.ImageField(blank=True, null=True, upload_to="documents/"),
                ),
                ("password", models.CharField(max_length=128)),
                ("confirm_password", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("office", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Urgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "office_name",
                    models.CharField(
                        choices=[
                            ("GAD Office", "GAD Office"),
                            ("VP Administration and Finance", "Admin and Finance"),
                            ("VP Academic Affairs", "VP Academic Affairs"),
                            (
                                "VP Students and External Affairs",
                                "VP Students and External Affairs",
                            ),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
