# Generated by Django 5.0.7 on 2024-08-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("office", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=50)),
                ("status", models.CharField(default="Pending", max_length=50)),
            ],
        ),
    ]
