# Generated by Django 5.0.7 on 2024-08-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="complaint_pdfs/"),
        ),
    ]
