# Generated by Django 5.1.1 on 2024-10-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0002_delete_message_remove_informant_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='receiving_office',
            field=models.CharField(choices=[('VP Administration and Finance', 'Admin and Finance'), ('VP Academic Affairs', 'VP Academic Affairs'), ('VP Students and External Affairs', 'VP Students and External Affairs'), ('GAD Office', 'GAD Office')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
