# Generated by Django 5.0.7 on 2024-08-18 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0004_alter_complaint_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="issue_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
