# Generated by Django 5.1.1 on 2024-10-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0005_alter_complaint_status_alter_complaint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Solved', 'Solved'), ('Pending', 'Pending'), ('In Progress', 'In Progress')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='type',
            field=models.CharField(choices=[('report', 'Report'), ('complaint', 'Complaint')], max_length=50),
        ),
    ]
