# Generated by Django 5.1.1 on 2024-10-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0006_alter_complaint_status_alter_complaint_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informant',
            name='document_file',
        ),
        migrations.RemoveField(
            model_name='informant',
            name='employee_id_file',
        ),
        migrations.RemoveField(
            model_name='informant',
            name='student_id_file',
        ),
        migrations.RemoveField(
            model_name='informant',
            name='study_load_file',
        ),
        migrations.AlterField(
            model_name='informant',
            name='department',
            field=models.CharField(blank=True, choices=[('STCS', 'School of Technology and Computer Science')], max_length=4, null=True),
        ),
    ]
