# Generated by Django 5.0.7 on 2024-08-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0006_complaint_is_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="office",
            field=models.CharField(
                choices=[
                    ("Admin Finance", "Admin Finance"),
                    ("Academic Affairs", "Academic Affairs"),
                    ("Students Affairs", "Students Affairs"),
                    ("GAD Office", "GAD Office"),
                    ("Legal Office", "Legal Office"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Resolved", "Resolved"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
