# Generated by Django 5.0.7 on 2024-08-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0008_alter_complaint_office_alter_complaint_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="office",
            field=models.CharField(
                choices=[
                    ("VP Administration and Finance", "Admin and Finance"),
                    ("VP Academic Affairs", "VP Academic Affairs"),
                    (
                        "VP Students and External Affairs",
                        "VP Students and External Affairs",
                    ),
                    ("GAD Office", "GAD Office"),
                ],
                max_length=50,
            ),
        ),
    ]
