# Generated by Django 5.1.1 on 2024-10-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0009_informant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
