# Generated by Django 5.0.7 on 2024-08-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0009_alter_complaint_office"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="office",
            field=models.CharField(
                choices=[
                    ("VP_Administration_and_Finance", "VP Administration and Finance"),
                    ("VP_Academic_Affairs", "VP Academic Affairs"),
                    (
                        "VP_Students_and_External_Affairs",
                        "VP Students and External Affairs",
                    ),
                    ("GAD_Office", "GAD Office"),
                    ("Legal_Office", "Legal Office"),
                ],
                max_length=50,
            ),
        ),
    ]
