# Generated by Django 5.0.7 on 2024-08-31 06:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0011_alter_complaint_office"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("office", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("status", models.CharField(max_length=50)),
                ("issue_date", models.DateTimeField()),
                (
                    "resolved_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appss.complaint",
                    ),
                ),
            ],
        ),
    ]
