# Generated by Django 5.1.1 on 2024-10-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0012_alter_informant_user'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informant',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='informant_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
