# Generated by Django 5.0.7 on 2024-08-31 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0012_complainthistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ComplaintHistory",
        ),
    ]
