# Generated by Django 5.0.7 on 2024-09-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0013_delete_complainthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="is_visible_in_academic_affairs_page",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="is_visible_in_admin_finance_page",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="is_visible_in_gad_office_page",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="is_visible_in_informant_page",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="is_visible_in_legal_office_page",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="is_visible_in_students_affairs_page",
            field=models.BooleanField(default=True),
        ),
    ]
