# Generated by Django 5.0.7 on 2024-09-01 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0014_complaint_is_visible_in_academic_affairs_page_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="is_visible_in_academic_affairs_page",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="is_visible_in_admin_finance_page",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="is_visible_in_gad_office_page",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="is_visible_in_informant_page",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="is_visible_in_legal_office_page",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="is_visible_in_students_affairs_page",
        ),
    ]
