# Generated by Django 5.0.7 on 2024-09-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0015_remove_complaint_is_visible_in_academic_affairs_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="urgency",
            field=models.CharField(
                choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")],
                default="Medium",
                max_length=6,
            ),
        ),
    ]
