# Generated by Django 5.1.1 on 2024-10-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0015_alter_informant_groups_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='user',
            new_name='informant',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='informant',
            name='user',
        ),
        migrations.AlterField(
            model_name='informant',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='informant_set', to='auth.permission'),
        ),
    ]
