# Generated by Django 5.0.7 on 2024-09-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0016_complaint_urgency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="urgency",
            field=models.CharField(
                choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")],
                max_length=6,
            ),
        ),
    ]
