# Generated by Django 5.1.1 on 2024-10-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0016_rename_user_office_informant_remove_complaint_is_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informant',
            name='document_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='informant',
            name='employee_id_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='informant',
            name='student_id_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='informant',
            name='study_load_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
