# Generated by Django 5.1.1 on 2024-10-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0018_complaint_informant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='informant',
        ),
    ]
