# Generated by Django 5.1.1 on 2024-10-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0020_complaint_informant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
