# Generated by Django 5.1.1 on 2024-10-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0021_alter_informant_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
