# Generated by Django 5.0.7 on 2024-09-04 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0021_alter_complaint_urgency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="urgency",
        ),
    ]
