# Generated by Django 5.0.7 on 2024-09-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0022_remove_complaint_urgency"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="urgency",
            field=models.CharField(
                choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")],
                default="Medium",
                max_length=10,
            ),
        ),
    ]
