# Generated by Django 5.1.1 on 2024-10-17 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0023_officeresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officeresponse',
            name='complaint',
        ),
        migrations.AddField(
            model_name='complaint',
            name='response_pdf',
            field=models.FileField(blank=True, null=True, upload_to='response_pdfs/'),
        ),
        migrations.AlterField(
            model_name='officeresponse',
            name='date_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='officeresponse',
            name='office',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='officeresponse',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='office_responses/'),
        ),
    ]
