# Generated by Django 5.1.1 on 2024-10-18 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0026_delete_officeresponse_remove_complaint_informant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='informant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Solved', 'Solved'), ('Pending', 'Pending'), ('In Progress', 'In Progress')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='type',
            field=models.CharField(choices=[('report', 'Report'), ('complaint', 'Complaint')], max_length=50),
        ),
    ]
