# Generated by Django 5.1.1 on 2024-10-18 04:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0027_complaint_informant_alter_complaint_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('response_pdf', models.FileField(blank=True, null=True, upload_to='response_pdfs/')),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='appss.complaint')),
            ],
        ),
    ]
