# Generated by Django 5.1.1 on 2024-10-18 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0028_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
