# Generated by Django 5.0.7 on 2024-09-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0028_urgency_alter_complaint_urgency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="urgency",
            field=models.CharField(
                choices=[("High", "High"), ("Low", "Low")], max_length=10
            ),
        ),
        migrations.DeleteModel(
            name="Urgency",
        ),
    ]
