# Generated by Django 5.0.7 on 2024-09-04 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0029_alter_complaint_urgency_delete_urgency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Urgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("High", "High"), ("Low", "Low")],
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="complaint",
            name="urgency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appss.urgency"
            ),
        ),
    ]
