# Generated by Django 5.1.1 on 2024-10-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0029_delete_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='response_pdf',
            field=models.FileField(blank=True, null=True, upload_to='response_pdfs/'),
        ),
    ]
