# Generated by Django 5.1.1 on 2024-10-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0030_complaint_response_date_complaint_response_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='response_date',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='response_pdf',
            field=models.FileField(blank=True, null=True, upload_to='responses/'),
        ),
    ]
