# Generated by Django 5.0.7 on 2024-09-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0030_urgency_alter_complaint_urgency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="urgency",
            field=models.BigIntegerField(default=0),
        ),
    ]
