# Generated by Django 5.0.7 on 2024-09-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0032_remove_complaint_urgency"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Urgency",
        ),
        migrations.AddField(
            model_name="complaint",
            name="urgency",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
