# Generated by Django 5.1.1 on 2024-10-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0032_letter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Letter',
        ),
    ]
