# Generated by Django 5.0.7 on 2024-09-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0034_urgency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="urgency",
            field=models.CharField(
                choices=[("High", "High"), ("Low", "Low")], max_length=10
            ),
        ),
    ]
