# Generated by Django 5.0.7 on 2024-09-05 06:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0035_alter_complaint_urgency"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Urgency",
        ),
    ]
