# Generated by Django 5.0.7 on 2024-09-05 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0036_delete_urgency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="urgency",
        ),
    ]
