# Generated by Django 5.1.1 on 2024-10-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0036_alter_complaint_response_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='response_pdf',
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_content', models.TextField()),
                ('response_pdf', models.FileField(blank=True, null=True, upload_to='responses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='appss.complaint')),
            ],
        ),
    ]
