# Generated by Django 5.0.7 on 2024-09-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0038_complaint_urgency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="urgency",
            field=models.CharField(max_length=50),
        ),
    ]
