# Generated by Django 5.1.1 on 2024-10-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0039_remove_complaint_response_pdf_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informant',
            name='document_file',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='informant',
            name='employee_id_file',
            field=models.ImageField(blank=True, null=True, upload_to='employee_ids/'),
        ),
        migrations.AlterField(
            model_name='informant',
            name='student_id_file',
            field=models.ImageField(blank=True, null=True, upload_to='student_ids/'),
        ),
        migrations.AlterField(
            model_name='informant',
            name='study_load_file',
            field=models.ImageField(blank=True, null=True, upload_to='study_loads/'),
        ),
    ]
