# Generated by Django 5.0.7 on 2024-09-05 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0040_urgency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="urgency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appss.urgency"
            ),
        ),
    ]
