# Generated by Django 5.1.1 on 2024-10-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0040_alter_informant_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informant',
            name='document_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='informant',
            name='employee_id_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='informant',
            name='student_id_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='informant',
            name='study_load_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
