# Generated by Django 5.1.1 on 2024-11-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0042_alter_informant_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Sexual Harassment', 'Sexual Harassment'), ('Sexual Assault', 'Sexual Assault'), ('Bullying', 'Bullying')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
