# Generated by Django 5.0.7 on 2024-09-05 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0043_urgency"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Urgency",
        ),
    ]
