# Generated by Django 5.1.1 on 2024-11-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0043_complaint_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(choices=[('GAD', 'Gender and Development'), ('AA', 'Academic Affairs'), ('AF', 'Admin and Finance'), ('SA', 'Student Affairs')], max_length=3)),
                ('department', models.CharField(choices=[('STCS', 'School of Technology and Computer Science'), ('SCJE', 'School of Criminal Justice and Education'), ('SAS', 'School of Arts and Sciences'), ('SME', 'School of Management and Entrepreneurship'), ('SOE', 'School of Engineering'), ('SNHS', 'School of Nursing and Health Sciences'), ('STED', 'School of Teacher Education')], max_length=4)),
                ('incident_content', models.TextField()),
            ],
        ),
    ]
