# Generated by Django 5.1.1 on 2024-11-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0044_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('sexual_harassment', 'Sexual Harassment'), ('sexual_assault', 'Sexual Assault'), ('bullying', 'Bullying')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Sexual Harassment', 'Sexual Harassment'), ('Sexual Assault', 'Sexual Assault'), ('Bullying', 'Bullying'), ('Financial Misconduct', 'Financial Misconduct'), ('Workplace Harassment', 'Workplace Harassment'), ('Academic Misconduct', 'Academic Misconduct'), ('Plagiarism', 'Plagiarism'), ('Student Misconduct', 'Student Misconduct'), ('Community Complaints', 'Community Complaints')], max_length=50),
        ),
    ]
