# Generated by Django 5.1.1 on 2024-11-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0045_incident_category_alter_complaint_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Sexual Harassment', 'Sexual Harassment'), ('Sexual Assault', 'Sexual Assault'), ('Bullying', 'Bullying')], max_length=50),
        ),
    ]
