# Generated by Django 5.0.7 on 2024-09-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appss", "0045_urgency_remove_complaint_urgency"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Urgency",
        ),
        migrations.AddField(
            model_name="complaint",
            name="urgency",
            field=models.CharField(default="low", max_length=50),
        ),
    ]
