# Generated by Django 5.1.1 on 2024-11-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0046_alter_complaint_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('sexual_harassment', 'Sexual Harassment'), ('sexual_assault', 'Sexual Assault'), ('bullying', 'Bullying'), ('discrimination', 'Discrimination'), ('abuse', 'Abuse'), ('violence', 'Violence'), ('gender_equality', 'Gender Equality'), ('defamation', 'Defamation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('sexual_harassment', 'Sexual Harassment'), ('sexual_assault', 'Sexual Assault'), ('bullying', 'Bullying'), ('discrimination', 'Discrimination'), ('abuse', 'Abuse'), ('violence', 'Violence'), ('gender_equality', 'Gender Equality'), ('defamation', 'Defamation')], max_length=20),
        ),
    ]
