# Generated by Django 5.1.1 on 2024-11-20 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0048_alter_complaint_category_alter_incident_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='informant',
        ),
        migrations.RemoveField(
            model_name='office',
            name='office_name',
        ),
        migrations.AddField(
            model_name='office',
            name='name',
            field=models.CharField(choices=[('GAD', 'Gender and Development'), ('VP_Admin_Finance', 'VP Administration and Finance'), ('VP_Academic_Affairs', 'VP Academic Affairs'), ('VP_Students_External', 'VP Students and External Affairs')], default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appss.office'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sexual Harassment', 'Sexual Harassment'), ('Sexual Assault', 'Sexual Assault'), ('Bullying', 'Bullying'), ('Discrimination', 'Discrimination'), ('Abuse', 'Abuse'), ('Violence', 'Violence'), ('Gender Equality', 'Gender Equality'), ('Defamation', 'Defamation'), ('Rape', 'Rape'), ('Financial Misconduct', 'Financial Misconduct'), ('Workplace Harassment', 'Workplace Harassment'), ('Academic Misconduct', 'Academic Misconduct'), ('Plagiarism', 'Plagiarism'), ('Student Misconduct', 'Student Misconduct'), ('Community Complaints', 'Community Complaints')], max_length=50)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='appss.office')),
            ],
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appss.category'),
        ),
    ]
