# Generated by Django 5.1.1 on 2024-11-20 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0049_remove_office_informant_remove_office_office_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('sexual_harassment', 'Sexual Harassment'), ('sexual_assault', 'Sexual Assault'), ('bullying', 'Bullying'), ('discrimination', 'Discrimination'), ('abuse', 'Abuse'), ('violence', 'Violence'), ('gender_equality', 'Gender Equality'), ('rape', 'Rape')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='office',
            name='name',
        ),
        migrations.AddField(
            model_name='office',
            name='informant',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='office_name',
            field=models.CharField(choices=[('GAD Office', 'GAD Office'), ('VP Administration and Finance', 'Admin and Finance'), ('VP Academic Affairs', 'VP Academic Affairs'), ('VP Students and External Affairs', 'VP Students and External Affairs')], default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='office',
            field=models.CharField(choices=[('GAD', 'Gender and Development'), ('AA', 'Academic Affairs'), ('AF', 'Admin and Finance'), ('SA', 'Student Affairs')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
