# Generated by Django 5.1.1 on 2024-11-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0050_alter_incident_category_remove_office_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('Sexual Harassment', 'Sexual Harassment'), ('Sexual Assault', 'Sexual Assault'), ('Bullying', 'Bullying'), ('Discrimination', 'Discrimination'), ('Abuse', 'Abuse'), ('Violence', 'Violence'), ('Gender Equality', 'Gender Equality'), ('Defamation', 'Defamation'), ('Rape', 'Rape')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='department',
            field=models.CharField(choices=[('STCS', 'School of Technology and Computer Science'), ('SCJE', 'School of Criminal Justice and Education'), ('SAS', 'School of Arts and Sciences'), ('SME', 'School of Management and Entrepreneurship'), ('SOE', 'School of Engineering'), ('SNHS', 'School of Nursing and Health Sciences'), ('STED', 'School of Teacher Education')], max_length=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='office',
            field=models.CharField(choices=[('GAD', 'Gender and Development'), ('VP_Admin_Finance', 'VP Admin and Finance'), ('VP_Academic_Affairs', 'VP Academic Affairs'), ('VP_Students_External', 'VP Students and External Affairs')], max_length=20),
        ),
    ]
