# Generated by Django 5.1.1 on 2024-11-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0051_alter_incident_category_alter_incident_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('sexual_harassment', 'Sexual Harassment'), ('sexual_assault', 'Sexual Assault'), ('bullying', 'Bullying'), ('discrimination', 'Discrimination'), ('abuse', 'Abuse'), ('violence', 'Violence'), ('gender_equality', 'Gender Equality'), ('rape', 'Rape'), ('financial_misconduct', 'Financial Misconduct')], max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='department',
            field=models.CharField(choices=[('STCS', 'School of Technology and Computer Science'), ('SCJE', 'School of Criminal Justice and Education'), ('SAS', 'School of Arts and Sciences'), ('SME', 'School of Management and Entrepreneurship'), ('SOE', 'School of Engineering'), ('SNHS', 'School of Nursing and Health Sciences'), ('STED', 'School of Teacher Education')], max_length=4),
        ),
        migrations.AlterField(
            model_name='incident',
            name='office',
            field=models.CharField(choices=[('GAD', 'Gender and Development'), ('AA', 'Academic Affairs'), ('AF', 'Admin and Finance'), ('SA', 'Student Affairs')], max_length=3),
        ),
    ]
