# Generated by Django 5.1.1 on 2024-11-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0052_alter_incident_category_alter_incident_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('sexual_harassment', 'Sexual Harassment'), ('sexual_assault', 'Sexual Assault'), ('bullying', 'Bullying'), ('discrimination', 'Discrimination'), ('abuse', 'Abuse'), ('violence', 'Violence'), ('gender_equality', 'Gender Equality'), ('rape', 'Rape'), ('financial_misconduct', 'Financial Misconduct')], max_length=50),
        ),
    ]
