# Generated by Django 5.1.1 on 2024-11-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appss', '0053_alter_complaint_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('sexual_harassment', 'Sexual Harassment'), ('sexual_assault', 'Sexual Assault'), ('bullying', 'Bullying'), ('discrimination', 'Discrimination'), ('abuse', 'Abuse'), ('violence', 'Violence'), ('gender_equality', 'Gender Equality'), ('rape', 'Rape')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('sexual_harassment', 'Sexual Harassment'), ('sexual_assault', 'Sexual Assault'), ('bullying', 'Bullying'), ('discrimination', 'Discrimination'), ('abuse', 'Abuse'), ('violence', 'Violence'), ('gender_equality', 'Gender Equality'), ('defamation', 'Defamation'), ('rape', 'Rape'), ('financial_issues', 'Financial Issues'), ('scholarship_issues', 'Scholarship Issues'), ('late_fees', 'Late Fees'), ('financial_aid', 'Financial Aid'), ('staff_payment_issues', 'Staff Payment Issues'), ('billing_errors', 'Billing Errors'), ('staff_academic_concerns', 'Staff and Academic Concerns'), ('tardiness', 'Tardiness'), ('always_late', 'Always Late'), ('favoritism', 'Favoritism'), ('always_absent', 'Always Absent'), ('unfair_grading', 'Unfair Grading'), ('unprofessional_behavior', 'Unprofessional Behavior'), ('student_related_issues', 'Student-Related Issues'), ('student_misconduct', 'Student Misconduct'), ('student_welfare', 'Student Welfare'), ('student_engagement', 'Student Engagement'), ('student_rights', 'Student Rights')], max_length=25),
        ),
    ]
